website/models.py
from pytz import timezone
from . import db
from flask_login import UserMixin
from sqlalchemy.sql import func


class Favorite(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    date = db.Column(db.DateTime(timezone=True), default=func.now())
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    product_id = db.Column(db.Integer, db.ForeignKey('product.id'))


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    first_name = db.Column(db.String(150))
    last_name = db.Column(db.String(150))
    favorite = db.relationship('Favorite')


class Product(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    product_name = db.Column(db.String(150), unique=True)
    product_desc = db.Column(db.String())
    product_pict = db.Column(db.String())
    price = db.Column(db.Integer)
    stock = db.Column(db.Integer)
    favorite = db.relationship('Favorite')


# class Product():

website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager

db = SQLAlchemy()
DB_NAME = "database.db"


def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'gsths stshthstr'
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    db.init_app(app)

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')

    from .models import User, Favorite

    create_database(app)

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))

    return app


def create_database(app):
    if not path.exists('website/' + DB_NAME):
        db.create_all(app=app)
        print('created database')

website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from flask_login import login_user, login_required, logout_user, current_user

auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Logged in Successfully!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.shop'))
            else:
                flash('Incorrect pass!', category='error')
        else:
            flash('Email doesnt exist', category='error')

    return render_template("auth/login.html", user=current_user)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('views.home'))


@auth.route('/signup', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        email = request.form.get('email')
        fname = request.form.get('fname')
        lname = request.form.get('lname')
        password = request.form.get('password')
        cpassword = request.form.get('cpassword')

        user = User.query.filter_by(email=email).first()
        if user:
            flash('Email already exists', category='error')
        elif len(email) < 4:
            flash('Email must be greater than 4 characters.', category='error')
        elif len(fname) < 2:
            flash('First name must be greater than 2 characters.', category='error')
        elif password != cpassword:
            flash('Password dont match.', category='error')
        elif len(password) < 7:
            flash('Password must be greater than 7 characters.', category='error')
        else:
            new_user = User(email=email, first_name=fname, last_name=lname,
                            password=generate_password_hash(password, method='sha256'))
            db.session.add(new_user)
            db.session.commit()
            flash('Account Created!', category='success')
            return redirect(url_for('auth.login'))

    return render_template("auth/sign_up.html")

website/views.py
from flask import Blueprint, render_template
from flask_login import login_required, current_user
from sqlalchemy import null

views = Blueprint('views', __name__)


@views.route('/')
def home():
    return render_template("home/home.html", user=current_user)


@views.route('/shop')
@login_required
def shop():
    return render_template("home/home.html", user=current_user)


@views.route('/product')
@login_required
def product():
    return render_template("home/product.html", user=current_user)


@views.route('/cake')
@login_required
def cake():
    return render_template("home/cake.html", user=current_user)


@views.route('/service')
@login_required
def service():
    return render_template("home/service.html", user=current_user)

website/templates/home/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="../../static/css/home.css">

    <title>{%block title %}Base{% endblock %}</title>
  </head>
  <body>

    <nav class="navbar navbar-light bg-light fixed-top">
      <div class="container">
        <a class="navbar-brand" href="#">Asan Shop</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
          <div class="offcanvas-header">
            <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Menu</h5>
            <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
          </div>
          <div class="offcanvas-body">
            <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="#">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('views.product') }}">Products</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('views.cake') }}">Cakes</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('views.service') }}">Services</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Chat</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="#">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('views.product') }}">Products</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('views.cake') }}">Cakes</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('views.service') }}">Services</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('auth.sign_up') }}">SignUp</a>
              </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </div>
    </nav>
    
    <div class="container" style="margin-top:80px">
      {% block content %}{% endblock %}
    </div>

    <footer class="container-fluid py-5 bg-light" style="margin-top: 30px;">
      <div class="row">
        <div class="col-12 col-md">
          <img class="img-fluid" src="../../static/main/logo.png">
          <small class="d-block mb-3 text-muted text-center">&copy; 2022-2023</small>
        </div>
        <div class="col-12 col-md">
          <h5>Products</h5>
          <ul class="list-unstyled text-small">
            <li>Electronik</li>
            <li>Perabotan rumah</li>
            <li>Alat Bangunan</li>
            <li>Kosmetik</li>
          </ul>
        </div>
        <div class="col-12 col-md">
          <h5>Address</h5>
          <ul class="list-unstyled text-small">
            <li>Jl.Kimaja - Lorong Arizona, Simpang III Sipin</li>
            <li>Kota Baru, Jambi</li>
            <li>Indonesia</li>
          </ul>
        </div>
        <div class="col-12 col-md">
          <h5>Other</h5>
          <ul class="list-unstyled text-small">
          <li>Cake</li>
          <li>Service</li>
          </ul>
        </div>
      </div>
    </footer>





    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

  </body>
</html>

website/templates/home/cake.html
{% extends "home/base.html" %}
{% block title %}Yanti's Cake Shop{% endblock %}

{% block content %}
<h1 class="title">Yanti's Cake Shop</h1>
<hr>
<br>
<h2 class="title">Your Favorite</h2>
<!-- kek yang geser geser carousel -->
<hr>
<h2 class="title">Cakes</h2>
<!-- pagination and card-->

<div class="new-product">
    <h2>New Product</h2>
    <div class="row">
        <div class="col-sm-3">
          <div class="card">
            <img src="..." class="card-img-top" alt="...">
            <div class="card-body">
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
            </div>
          </div>
        </div>
        <div class="col-sm-3">
          <div class="card">
            <img src="..." class="card-img-top" alt="...">
            <div class="card-body">
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
            </div>
          </div>
        </div>
        <div class="col-sm-3">
            <div class="card">
              <img src="..." class="card-img-top" alt="...">
              <div class="card-body">
                  <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
              </div>
            </div>
        </div>
        <div class="col-sm-3">
            <div class="card">
              <img src="..." class="card-img-top" alt="...">
              <div class="card-body">
                  <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
              </div>
            </div>
        </div>
      </div>
</div>

<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
        <li class="page-item disabled">
        <a class="page-link">Previous</a>
        </li>
        <li class="page-item"><a class="page-link" href="#">1</a></li>
        <li class="page-item"><a class="page-link" href="#">2</a></li>
        <li class="page-item"><a class="page-link" href="#">3</a></li>
        <li class="page-item">
        <a class="page-link" href="#">Next</a>
        </li>
    </ul>
</nav>
{% endblock %}

website/templates/home/chat.html
{% extends "home/base.html" %}
{% block title %}Chat{% endblock %} 

website/templates/home/home.html
{% extends "home/base.html" %}
{% block title %}Home{% endblock %} 

{% block content %}
<h1 class="title">Asan Arizona</h1>
<hr>
<p class="desc">Menyediakan kebutuhan rumah, listrik, bangunan, kue dan layanan service elektronik </p>

<div class="about">
    <div class="shop-picture">
        <div class="shop-picture-div">
            <img src="../../static/main/test1.jpg" alt="">
        </div>
    </div>
    <div class="shop-desc">
        <h2 class="desc-title">Tentang Toko</h2>
        <p class="desc-desc">
            Toko Asan merupakan toko yang serba ada / Toserba. 
        </p>
        <p class="desc-ket">

        </p>
    </div>
</div>


<div class="new-product">
    <h2>New Product</h2>
    <div class="row">
        <div class="col-sm-3">
          <div class="card">
            <img src="..." class="card-img-top" alt="...">
            <div class="card-body">
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
            </div>
          </div>
        </div>
        <div class="col-sm-3">
          <div class="card">
            <img src="..." class="card-img-top" alt="...">
            <div class="card-body">
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
            </div>
          </div>
        </div>
        <div class="col-sm-3">
            <div class="card">
              <img src="..." class="card-img-top" alt="...">
              <div class="card-body">
                  <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
              </div>
            </div>
        </div>
        <div class="col-sm-3">
            <div class="card">
              <img src="..." class="card-img-top" alt="...">
              <div class="card-body">
                  <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
              </div>
            </div>
        </div>
      </div>
</div>


<div class="best-product">
    <h2>Best Seller</h2>
    <div class="row">
        <div class="col-sm-3">
          <div class="card">
            <img src="..." class="card-img-top" alt="...">
            <div class="card-body">
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
            </div>
          </div>
        </div>
        <div class="col-sm-3">
          <div class="card">
            <img src="..." class="card-img-top" alt="...">
            <div class="card-body">
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
            </div>
          </div>
        </div>
        <div class="col-sm-3">
            <div class="card">
              <img src="..." class="card-img-top" alt="...">
              <div class="card-body">
                  <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
              </div>
            </div>
        </div>
        <div class="col-sm-3">
            <div class="card">
              <img src="..." class="card-img-top" alt="...">
              <div class="card-body">
                  <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
              </div>
            </div>
        </div>
      </div>
</div>
{% endblock %}

website/templates/home/product.html
{% extends "home/base.html" %}
{% block title %}Product{% endblock %}


{% block content %}
<h1 class="title">Product Shop</h1>
<hr>
<br>
<h2 class="title">Your Favorite</h2>
<!-- kek yang geser geser carousel -->
<hr>
<h2 class="title">Products</h2>
<!-- pagination and card-->
{% endblock %}

website/templates/home/service.html
{% extends "home/base.html" %}
{% block title %}Electronic Service{% endblock %}

{% block content %}

{% endblock %}